### ISSUE TITLE
Can't compile on Linux Mint 19.3

### ISSUE THREAD

**Issue by janoleholm** [righthalfplane/SdrGlut#17]
Want to try your sdr with my LimeSDR mini, but get this error:

Radio/RaceFastsdr.cpp:1199:50: error: invalid conversion from ‘int’ to ‘liquid_ampmodem_type’ [-fpermissive]
     f->demodAM = ampmodem_create(0.5, mode, iflag);
                                                  ^
Radio/RaceFastsdr.cpp:1199:50: error: too few arguments to function ‘ampmodem_s* ampmodem_create(float, float, liquid_ampmodem_type, int)’

**Comment by righthalfplane** [comment]
In the file MainSource/firstFile.h comment out the "#if LIQUID_VERSION_NUMBER >= 1003001 || __arm__" like -

//#if LIQUID_VERSION_NUMBER >= 1003001 || __arm__
#define LIQUID_VERSION_4 1
//#endif

**Comment by janoleholm** [comment]
Thanks very much.

Now I compile without errors :-)
